import { Event, Post, Notification } from "../../types";

let mockEvents: Event[] = [
  {
    id: 1,
    name: "Noite de Forró",
    type: "artes",
    location: "Parque do Povo",
    position: [-7.2305, -35.8811],
    attendees: 18,
    date: "Hoje à noite",
    time: "20:00",
    startsAt: "2026-01-20T20:00:00-03:00",
    endsAt: "2026-01-20T23:00:00-03:00",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400",
    description: "Forró tradicional com as melhores bandas da região",
    distanceKm: 3.2,
    maxAttendees: 20,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: true,
  },
  {
    id: 2,
    name: "Café & Código",
    type: "estudo",
    location: "CEEI - UFCG",
    position: [-7.2159, -35.9108],
    attendees: 12,
    date: "Amanhã",
    time: "10:00",
    startsAt: "2026-01-21T10:00:00-03:00",
    endsAt: "2026-01-21T12:00:00-03:00",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    description: "Networking para desenvolvedores e tech enthusiasts",
    distanceKm: 5.6,
    maxAttendees: 20,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: false,
  },
  {
    id: 3,
    name: "Festival Gastronômico",
    type: "lazer",
    location: "Açude Velho",
    position: [-7.2188, -35.8817],
    attendees: 20,
    date: "Este fim de semana",
    time: "12:00",
    startsAt: "2026-01-24T12:00:00-03:00",
    endsAt: "2026-01-24T16:00:00-03:00",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    description: "Sabores de Campina Grande e região",
    distanceKm: 2.1,
    maxAttendees: 20,
    visibility: "friends",
    requiresApproval: true,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: false,
  },
  {
    id: 4,
    name: "Meetup de Tech",
    type: "estudo",
    location: "LCC - UFCG",
    position: [-7.2145, -35.9087],
    attendees: 9,
    date: "Próxima semana",
    time: "18:00",
    startsAt: "2026-01-27T18:00:00-03:00",
    endsAt: "2026-01-27T21:00:00-03:00",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400",
    description: "Discussões sobre IA, Web3 e o futuro da tech",
    distanceKm: 6.8,
    maxAttendees: 20,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: false,
    genderFocus: "all",
    isRecurring: true,
  },
  {
    id: 5,
    name: "Show Universitário",
    type: "artes",
    location: "Bodódromo",
    position: [-7.2197, -35.8923],
    attendees: 16,
    date: "Sexta-feira",
    time: "21:00",
    startsAt: "2026-01-23T21:00:00-03:00",
    endsAt: "2026-01-23T23:30:00-03:00",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400",
    description: "Bandas locais e muita energia",
    distanceKm: 4.4,
    maxAttendees: 20,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: false,
  },
  {
    id: 6,
    name: "Yoga no Parque",
    type: "esportes",
    location: "Parque da Criança",
    position: [-7.2278, -35.8845],
    attendees: 8,
    date: "Sábado",
    time: "07:00",
    startsAt: "2026-01-24T07:00:00-03:00",
    endsAt: "2026-01-24T09:00:00-03:00",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    description: "Prática matinal ao ar livre",
    distanceKm: 1.7,
    maxAttendees: 12,
    visibility: "invite-only",
    requiresApproval: true,
    isLgbtFriendly: true,
    genderFocus: "women",
    isRecurring: true,
  },
  {
    id: 7,
    name: "Corrida no Açude",
    type: "esportes",
    location: "Açude Velho",
    position: [-7.2188, -35.8817],
    attendees: 15,
    date: "Domingo",
    time: "06:30",
    startsAt: "2026-01-25T06:30:00-03:00",
    endsAt: "2026-01-25T08:00:00-03:00",
    image: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=400",
    description: "Corrida matinal em grupo ao redor do açude",
    distanceKm: 2.3,
    maxAttendees: 30,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: true,
  },
  {
    id: 8,
    name: "Crossfit ao Ar Livre",
    type: "esportes",
    location: "Parque do Povo",
    position: [-7.2305, -35.8811],
    attendees: 12,
    date: "Segunda-feira",
    time: "18:00",
    startsAt: "2026-01-26T18:00:00-03:00",
    endsAt: "2026-01-26T19:30:00-03:00",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
    description: "Treino funcional intenso em grupo",
    distanceKm: 3.5,
    maxAttendees: 20,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: true,
  },
  {
    id: 9,
    name: "Passeio de Bicicleta",
    type: "esportes",
    location: "Centro - Ponto de Encontro",
    position: [-7.2159, -35.9108],
    attendees: 20,
    date: "Terça-feira",
    time: "17:00",
    startsAt: "2026-01-27T17:00:00-03:00",
    endsAt: "2026-01-27T19:00:00-03:00",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400",
    description: "Passeio ciclístico pela cidade",
    distanceKm: 8.5,
    maxAttendees: 25,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: false,
  },
  {
    id: 101,
    name: "Sarau Cultural",
    type: "artes",
    location: "Centro Histórico",
    position: [-7.2212, -35.8789],
    attendees: 22,
    date: "Semana passada",
    time: "19:00",
    startsAt: "2026-01-18T19:00:00-03:00",
    endsAt: "2026-01-18T22:00:00-03:00",
    image: "https://images.unsplash.com/photo-1497032205916-ac775f0649ae?w=400",
    description: "Poemas, música ao vivo e apresentações artísticas",
    distanceKm: 2.9,
    maxAttendees: 30,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: false,
  },
  {
    id: 102,
    name: "Feira Criativa",
    type: "lazer",
    location: "Praça Central",
    position: [-7.2228, -35.8833],
    attendees: 40,
    date: "Semana passada",
    time: "10:00",
    startsAt: "2026-01-19T10:00:00-03:00",
    endsAt: "2026-01-19T14:00:00-03:00",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=400",
    description: "Artesanato, gastronomia e produtos autorais",
    distanceKm: 3.5,
    maxAttendees: 50,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: false,
  },
  {
    id: 103,
    name: "Cinema ao Ar Livre",
    type: "lazer",
    location: "Praça da Bandeira",
    position: [-7.2236, -35.8872],
    attendees: 55,
    date: "Duas semanas atrás",
    time: "19:30",
    startsAt: "2026-01-10T19:30:00-03:00",
    endsAt: "2026-01-10T22:00:00-03:00",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400",
    description: "Sessão gratuita com telão e pipoca na praça",
    distanceKm: 4.1,
    maxAttendees: 80,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: false,
  },
  {
    id: 104,
    name: "Encontro de Fotografia",
    type: "artes",
    location: "Parque da Criança",
    position: [-7.2278, -35.8845],
    attendees: 28,
    date: "Duas semanas atrás",
    time: "16:00",
    startsAt: "2026-01-12T16:00:00-03:00",
    endsAt: "2026-01-12T18:30:00-03:00",
    image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400",
    description: "Passeio fotográfico e troca de técnicas",
    distanceKm: 3.0,
    maxAttendees: 35,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: false,
  },
  {
    id: 10,
    name: "Natação no Clube",
    type: "esportes",
    location: "Clube Campestre",
    position: [-7.225, -35.895],
    attendees: 10,
    date: "Quarta-feira",
    time: "07:00",
    startsAt: "2026-01-28T07:00:00-03:00",
    endsAt: "2026-01-28T08:30:00-03:00",
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=400",
    description: "Treino de natação em grupo",
    distanceKm: 4.2,
    maxAttendees: 15,
    visibility: "friends",
    requiresApproval: true,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: true,
  },
  {
    id: 11,
    name: "Futebol Amador",
    type: "esportes",
    location: "Campo do Borborema",
    position: [-7.22, -35.89],
    attendees: 18,
    date: "Quinta-feira",
    time: "19:00",
    startsAt: "2026-01-29T19:00:00-03:00",
    endsAt: "2026-01-29T21:00:00-03:00",
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400",
    description: "Pelada semanal para todos os níveis",
    distanceKm: 5.1,
    maxAttendees: 22,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: true,
  },
  {
    id: 12,
    name: "Meditação Guiada",
    type: "esportes",
    location: "Jardim Botânico",
    position: [-7.222, -35.888],
    attendees: 14,
    date: "Sexta-feira",
    time: "18:30",
    startsAt: "2026-01-30T18:30:00-03:00",
    endsAt: "2026-01-30T19:30:00-03:00",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400",
    description: "Sessão de meditação e relaxamento",
    distanceKm: 3.8,
    maxAttendees: 20,
    visibility: "public",
    requiresApproval: false,
    isLgbtFriendly: true,
    genderFocus: "all",
    isRecurring: true,
  },
];

let mockPosts: Post[] = [
  {
    id: 1,
    event: {
      name: "Meetup de Tech",
      location: "LCC - UFCG",
      date: "Ontem",
    },
    image:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWNoJTIwbWVldHVwJTIwcG9kY2FzdCUyMGdyb3VwfGVufDF8fHx8MTczNjc1NDkyMjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    attendees: [
      { name: "Ana Silva", avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Carlos Oliveira", avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Beatriz Santos", avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Rafael Costa", avatar: "https://i.pravatar.cc/150?img=7" },
    ],
    totalAttendees: 67,
    likes: 234,
    comments: 18,
    timeAgo: "há 2h",
    caption: "Discussões incríveis sobre IA e Web3! 🚀",
    author: {
      id: 2,
      username: "ana_tech",
      name: "Ana Silva",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    isEventPost: false,
  },
  {
    id: 2,
    event: {
      name: "Noite de Forró",
      location: "Parque do Povo",
      date: "Sábado",
    },
    image:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb3JybyUyMGRhbmNlJTIwcGFydHl8ZW58MXx8fHwxNzM2NzU0OTIyNnww&ixlib=rb-4.1.0&q=80&w=1080",
    attendees: [
      { name: "Mariana Lima", avatar: "https://i.pravatar.cc/150?img=9" },
      { name: "João Pedro", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Fernanda Rocha", avatar: "https://i.pravatar.cc/150?img=23" },
    ],
    totalAttendees: 245,
    likes: 456,
    comments: 32,
    timeAgo: "há 5h",
    caption: "A noite mais animada de Campina! 🎵🔥",
    author: {
      id: 6,
      username: "mariana_lima",
      name: "Mariana Lima",
      avatar: "https://i.pravatar.cc/150?img=9",
    },
    isEventPost: false,
  },
  {
    id: 3,
    event: {
      name: "Festival Gastronômico",
      location: "Açude Velho",
      date: "Domingo",
    },
    image:
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb29kJTIwZmVzdGl2YWwlMjBzdHJlZXR8ZW58MXx8fHwxNzM2NzU0OTIyN3ww&ixlib=rb-4.1.0&q=80&w=1080",
    attendees: [
      { name: "Lucas Almeida", avatar: "https://i.pravatar.cc/150?img=14" },
      { name: "Camila Torres", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Pedro Henrique", avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Julia Martins", avatar: "https://i.pravatar.cc/150?img=20" },
      { name: "Diego Silva", avatar: "https://i.pravatar.cc/150?img=33" },
    ],
    totalAttendees: 456,
    likes: 589,
    comments: 45,
    timeAgo: "há 1d",
    caption: "Sabores incríveis da nossa região! 🍴😋",
    author: {
      id: 9,
      username: "lucas_almeida",
      name: "Lucas Almeida",
      avatar: "https://i.pravatar.cc/150?img=14",
    },
    isEventPost: false,
  },
  {
    id: 4,
    event: {
      name: "Café & Código",
      location: "CEEI - UFCG",
      date: "Sexta-feira",
    },
    image:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2RpbmclMjBjb2ZmZWUlMjBsYXB0b3B8ZW58MXx8fHwxNzM2NzU0OTIyN3ww&ixlib=rb-4.1.0&q=80&w=1080",
    attendees: [
      { name: "Thiago Santos", avatar: "https://i.pravatar.cc/150?img=52" },
      { name: "Amanda Costa", avatar: "https://i.pravatar.cc/150?img=45" },
    ],
    totalAttendees: 23,
    likes: 187,
    comments: 12,
    timeAgo: "há 2d",
    caption: "Networking e muito código! ☕💻",
    author: {
      id: 14,
      username: "thiago_santos",
      name: "Thiago Santos",
      avatar: "https://i.pravatar.cc/150?img=52",
    },
    isEventPost: false,
  },
  {
    id: 5,
    event: {
      name: "Corrida no Açude",
      location: "Açude Velho",
      date: "Domingo",
    },
    image:
      "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=1080",
    attendees: [
      { name: "Você", avatar: "https://i.pravatar.cc/150?img=50" },
      { name: "Pedro Henrique", avatar: "https://i.pravatar.cc/150?img=18" },
      { name: "Camila Torres", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Lucas Almeida", avatar: "https://i.pravatar.cc/150?img=14" },
    ],
    totalAttendees: 15,
    likes: 89,
    comments: 7,
    timeAgo: "há 3d",
    caption: "Domingo perfeito para uma corrida matinal! 🌅🏃‍♂️",
    author: {
      id: 1,
      username: "fabiano_silva",
      name: "Fabiano Silva",
      avatar: "https://i.pravatar.cc/150?img=50",
    },
    isEventPost: false,
  },
  {
    id: 6,
    event: {
      name: "Crossfit ao Ar Livre",
      location: "Parque do Povo",
      date: "Segunda-feira",
    },
    image:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1080",
    attendees: [
      { name: "Julia Martins", avatar: "https://i.pravatar.cc/150?img=20" },
      { name: "Diego Silva", avatar: "https://i.pravatar.cc/150?img=33" },
      { name: "Mariana Lima", avatar: "https://i.pravatar.cc/150?img=9" },
    ],
    totalAttendees: 12,
    likes: 156,
    comments: 14,
    timeAgo: "há 4d",
    caption: "Treino pesado mas valeu a pena! 💪🔥",
    author: {
      id: 12,
      username: "julia_martins",
      name: "Julia Martins",
      avatar: "https://i.pravatar.cc/150?img=20",
    },
    isEventPost: false,
  },
  {
    id: 7,
    event: {
      name: "Passeio de Bicicleta",
      location: "Centro - Ponto de Encontro",
      date: "Terça-feira",
    },
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1080",
    attendees: [
      { name: "Rafael Costa", avatar: "https://i.pravatar.cc/150?img=7" },
      { name: "Beatriz Santos", avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Você", avatar: "https://i.pravatar.cc/150?img=50" },
    ],
    totalAttendees: 20,
    likes: 234,
    comments: 19,
    timeAgo: "há 5d",
    caption: "Passeio incrível pela cidade! 🚴‍♀️✨",
    author: {
      id: 5,
      username: "rafael_costa",
      name: "Rafael Costa",
      avatar: "https://i.pravatar.cc/150?img=7",
    },
    isEventPost: false,
  },
  {
    id: 8,
    event: {
      name: "Natação no Clube",
      location: "Clube Campestre",
      date: "Quarta-feira",
    },
    image:
      "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=1080",
    attendees: [
      { name: "Ana Silva", avatar: "https://i.pravatar.cc/150?img=1" },
      { name: "Carlos Oliveira", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    totalAttendees: 10,
    likes: 67,
    comments: 5,
    timeAgo: "há 6d",
    caption: "Manhã refrescante na piscina! 🏊‍♂️💙",
    author: {
      id: 2,
      username: "ana_tech",
      name: "Ana Silva",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    isEventPost: false,
  },
  {
    id: 9,
    event: {
      name: "Futebol Amador",
      location: "Campo do Borborema",
      date: "Quinta-feira",
    },
    image:
      "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=1080",
    attendees: [
      { name: "João Pedro", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Fernanda Rocha", avatar: "https://i.pravatar.cc/150?img=23" },
      { name: "Você", avatar: "https://i.pravatar.cc/150?img=50" },
      { name: "Thiago Santos", avatar: "https://i.pravatar.cc/150?img=52" },
    ],
    totalAttendees: 18,
    likes: 312,
    comments: 28,
    timeAgo: "há 1 semana",
    caption: "Pelada da semana! Que jogo! ⚽🎯",
    author: {
      id: 1,
      username: "fabiano_silva",
      name: "Fabiano Silva",
      avatar: "https://i.pravatar.cc/150?img=50",
    },
    isEventPost: false,
  },
  {
    id: 10,
    event: {
      name: "Meditação Guiada",
      location: "Jardim Botânico",
      date: "Sexta-feira",
    },
    image:
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1080",
    attendees: [
      { name: "Amanda Costa", avatar: "https://i.pravatar.cc/150?img=45" },
      { name: "Você", avatar: "https://i.pravatar.cc/150?img=50" },
      { name: "Camila Torres", avatar: "https://i.pravatar.cc/150?img=16" },
    ],
    totalAttendees: 14,
    likes: 98,
    comments: 9,
    timeAgo: "há 1 semana",
    caption: "Momentos de paz e tranquilidade 🧘‍♀️🌸",
    author: {
      id: 15,
      username: "amanda_costa",
      name: "Amanda Costa",
      avatar: "https://i.pravatar.cc/150?img=45",
    },
    isEventPost: false,
  },
  // Posts oficiais de eventos (sem autor)
  {
    id: 1001,
    event: {
      name: "Noite de Forró",
      location: "Parque do Povo",
      date: "Hoje",
    },
    image:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1080",
    attendees: [
      { name: "Mariana Lima", avatar: "https://i.pravatar.cc/150?img=9" },
      { name: "João Pedro", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Fernanda Rocha", avatar: "https://i.pravatar.cc/150?img=23" },
    ],
    totalAttendees: 245,
    likes: 1234,
    comments: 89,
    timeAgo: "há 1h",
    isEventPost: true,
  },
  {
    id: 1002,
    event: {
      name: "Show Universitário",
      location: "Bodódromo",
      date: "Sexta-feira",
    },
    image:
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1080",
    attendees: [
      { name: "Rafael Costa", avatar: "https://i.pravatar.cc/150?img=7" },
      { name: "Beatriz Santos", avatar: "https://i.pravatar.cc/150?img=5" },
      { name: "Carlos Oliveira", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    totalAttendees: 156,
    likes: 987,
    comments: 67,
    timeAgo: "há 3h",
    isEventPost: true,
  },
  {
    id: 1003,
    event: {
      name: "Yoga no Parque",
      location: "Parque da Criança",
      date: "Sábado",
    },
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1080",
    attendees: [
      { name: "Amanda Costa", avatar: "https://i.pravatar.cc/150?img=45" },
      { name: "Camila Torres", avatar: "https://i.pravatar.cc/150?img=16" },
      { name: "Julia Martins", avatar: "https://i.pravatar.cc/150?img=20" },
    ],
    totalAttendees: 12,
    likes: 345,
    comments: 23,
    timeAgo: "há 6h",
    isEventPost: true,
  },
  {
    id: 1004,
    event: {
      name: "Sarau Cultural",
      location: "Centro Histórico",
      date: "Semana passada",
    },
    image:
      "https://images.unsplash.com/photo-1454922915609-78549ad709bb?w=1080",
    images: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1080",
      "https://images.unsplash.com/photo-1497032205916-ac775f0649ae?w=1080",
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1080",
    ],
    attendees: [
      { name: "Mariana Lima", avatar: "https://i.pravatar.cc/150?img=9" },
      { name: "João Pedro", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Fernanda Rocha", avatar: "https://i.pravatar.cc/150?img=23" },
    ],
    totalAttendees: 72,
    likes: 543,
    comments: 41,
    timeAgo: "há 3d",
    isEventPost: true,
  },
  {
    id: 1005,
    event: {
      name: "Feira Criativa",
      location: "Praça Central",
      date: "Semana passada",
    },
    image:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1080",
    images: [
      "https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=1080",
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1080",
      "https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?w=1080",
    ],
    attendees: [
      { name: "Amanda Costa", avatar: "https://i.pravatar.cc/150?img=45" },
      { name: "Carlos Oliveira", avatar: "https://i.pravatar.cc/150?img=3" },
      { name: "Beatriz Santos", avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    totalAttendees: 98,
    likes: 612,
    comments: 56,
    timeAgo: "há 4d",
    isEventPost: true,
  },
  {
    id: 1006,
    event: {
      name: "Cinema ao Ar Livre",
      location: "Praça da Bandeira",
      date: "Duas semanas atrás",
    },
    image:
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1080",
    images: [
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1080",
      "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1080",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1080",
    ],
    attendees: [
      { name: "João Pedro", avatar: "https://i.pravatar.cc/150?img=12" },
      { name: "Fernanda Rocha", avatar: "https://i.pravatar.cc/150?img=23" },
      { name: "Carlos Oliveira", avatar: "https://i.pravatar.cc/150?img=3" },
    ],
    totalAttendees: 140,
    likes: 812,
    comments: 73,
    timeAgo: "há 2 semanas",
    isEventPost: true,
  },
  {
    id: 1007,
    event: {
      name: "Encontro de Fotografia",
      location: "Parque da Criança",
      date: "Duas semanas atrás",
    },
    image:
      "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=1080",
    images: [
      "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=1080",
      "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1080",
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1080",
    ],
    attendees: [
      { name: "Mariana Lima", avatar: "https://i.pravatar.cc/150?img=9" },
      { name: "Amanda Costa", avatar: "https://i.pravatar.cc/150?img=45" },
      { name: "Beatriz Santos", avatar: "https://i.pravatar.cc/150?img=5" },
    ],
    totalAttendees: 64,
    likes: 489,
    comments: 38,
    timeAgo: "há 2 semanas",
    isEventPost: true,
  },
];

// Função para adicionar um novo post
export const addPost = (post: Post) => {
  mockPosts = [post, ...mockPosts];
};

// Função para obter os posts
export const getMockPosts = (): Post[] => mockPosts;

// Export para compatibilidade (mantém o mesmo nome)
export { mockPosts };

let mockNotifications: Notification[] = [
  {
    id: 1,
    type: "comment",
    user: "Ana Silva",
    avatar: "https://i.pravatar.cc/150?img=1",
    message: "comentou no Meetup de Tech que você participou",
    time: "5 min",
    unread: true,
  },
  {
    id: 2,
    type: "connection",
    user: "Carlos Oliveira",
    avatar: "https://i.pravatar.cc/150?img=3",
    userId: 3, // ID do usuário que enviou a solicitação
    message: "quer conectar com você",
    time: "1h",
    unread: true,
  },
  {
    id: 3,
    type: "event",
    message: "Noite de Forró começa em 2 horas",
    time: "2h",
    unread: true,
  },
  {
    id: 4,
    type: "reminder",
    message: "Café & Código amanhã às 10h",
    time: "3h",
    unread: false,
  },
  {
    id: 5,
    type: "comment",
    user: "Beatriz Santos",
    avatar: "https://i.pravatar.cc/150?img=5",
    message: "comentou no Festival Gastronômico que você participou",
    time: "5h",
    unread: false,
  },
  {
    id: 6,
    type: "event",
    message: "Meetup de Tech - 67 pessoas confirmadas",
    time: "1d",
    unread: false,
  },
  {
    id: 7,
    type: "connection",
    user: "Rafael Costa",
    avatar: "https://i.pravatar.cc/150?img=7",
    userId: 5, // ID do usuário que enviou a solicitação
    message: "quer conectar com você",
    time: "2d",
    unread: false,
  },
];

// Funções para gerenciar eventos
export const getMockEvents = (): Event[] => mockEvents;

export const addEvent = (event: Event) => {
  mockEvents = [event, ...mockEvents];
};

// Funções para gerenciar notificações
export const getMockNotifications = (): Notification[] => mockNotifications;

export const markNotificationAsRead = (id: number) => {
  const notification = mockNotifications.find((n) => n.id === id);
  if (notification) {
    notification.unread = false;
  }
};

export const removeNotification = (id: number) => {
  mockNotifications = mockNotifications.filter((n) => n.id !== id);
};

// Export para compatibilidade
export { mockEvents, mockNotifications };
